import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * everything in this file is going to display across
 * all webpages of this app. So this makes a great place to
 * put things like navbars, footers, scripts, metadata, fonts
 */

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
